name: Research Note Immutable Timestamp

on:
  release:
    types: [published]
  workflow_dispatch: # 수동 실행 버튼 활성화

permissions:
  contents: write
  id-token: write

jobs:
  timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 에러가 나던 버전을 @main으로 수정했습니다
      - name: Create Trusted Timestamp
        uses: timestampit/github_action@main
        with:
          branch: 'trusted_timestamps'
